server:
  port: 8082
spring:
  application:
    name: oss-service
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7200/eureka
    registry-fetch-interval-seconds: 15
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
by:
  oss:
    accessKeyId: LTAI4G8x5FaMBokmocXk13Tc
    accessKeySecret: qKeLggngdlCx0vqq3EwhqzqlFFXEag
    host: http://boyue-oss.oss-cn-beijing.aliyuncs.com # 访问oss的域名，很重要bucket + endpoint
    endpoint: oss-cn-beijing.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: boyue-image/ # 保存到bucket的某个子目录
    expireTime: 120 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M
logging:
  config:
    classpath: logback-spring.xml
  path: D:/GraduationProject/BoYue/boyue-logback/upload