server:
  port: 7200
spring:
  application:
    name: by-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7200/eureka
    fetch-registry: false
    register-with-eureka: false