server:
  port: 10010
spring:
  application:
    name: by-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7200/eureka
    registry-fetch-interval-seconds: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500      # ribbon链接超时时长
  ReadTimeout: 2000        # ribbon读取超时时长
  MaxAutoRetries: 0        # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**      # 商品微服务       /item/**
    oss-service: /upload/**     # 文件管理微服务   /upload/**
    search-service: /search/**  # 搜索微服务       /search/**
by:
  cors:
    allowedOrigins:
      - http://manage.boyue.com
      - http://www.boyue.com
      - http://image.boyue.com;
    allowedCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"
logging:
  config:
    classpath: logback-spring.xml
  path: D:/GraduationProject/BoYue/boyue-logback/zuul
